version: "3"
services:
  api:
    build: .
    command: "npm start"
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    volumes:
      - "./src:/app/src"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
